### ISSUE TITLE
Create unit test for organization attributes

### ISSUE THREAD

**Issue by SamsonDeVol** [SamsonDeVol/cs362-coad-resources#13]
Attributes include: email, name, phone, status, primary_name, secondary_name, secondary_phone

**Comment by SamsonDeVol** [comment]
All organization attributes needed to be tested have unit tests

**Comment by SamsonDeVol** [comment]
TODO: add attr_attribute tests

**Comment by stalberm** [comment]
Separate attr_accessor attributes into separate tests
